FormularioNOW/Controllers/GeralController.cs
using FormularioNOW.DAO;
using FormularioNOW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormularioNOW.Controllers
{
    [Authorize]
    public class GeralController : Controller
    {
        #region Geral
        [HttpGet]
        public ActionResult Index()
        {
            List<NOW> ListaNow = new List<NOW>();
            ListaNow = NowDAO.listar();
            return View(ListaNow);
        }
        
        [HttpGet]
        public ActionResult GerarNOW()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GerarNOW(NOW now)
        {
            DAO.NowDAO.Cadastrar(now);
            return RedirectToAction("Index");
        }
        #endregion

        [HttpGet]
        public ActionResult DetalhesNOW(int Id)
        {
            NOW Now = DAO.NowDAO.pesquisarID(Id);
            return View(Now);
        }

        [HttpGet]
        public ActionResult Pesquisar(string pesquisa)
        {
            List<NOW> ListaNow = new List<NOW>();
            if (pesquisa == null)
            {
                ListaNow = NowDAO.listar();
            }
            else
            {
                ListaNow = NowDAO.pesquisarNome(pesquisa);
            }
            return View(ListaNow);
        }

    }
}

FormularioNOW/Controllers/ProdSoftController.cs
using FormularioNOW.DAO;
using FormularioNOW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormularioNOW.Controllers
{
    [Authorize]
    public class ProdSoftController : Controller
    {
        #region Geral
        [HttpGet]
        public ActionResult Index()
        {
            List<NOW> ListaNow = new List<NOW>();
            ListaNow = ProdSoftDAO.listar();
            return View(ListaNow);
        }

        [HttpGet]
        public ActionResult ProdSoftNOW(int Id_Now)
        {
            NOW now = NowDAO.pesquisarID(Id_Now);
            return View(now);
        }

        [HttpPost]
        public ActionResult ProdSoftNOW(NOW now)
        {
            ProdSoftDAO.CadastrarProdSoft(now);
            return RedirectToAction("Index");
        }
        #endregion
    }
}

FormularioNOW/Controllers/TiController.cs
using FormularioNOW.DAO;
using FormularioNOW.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FormularioNOW.Controllers
{
    [Authorize]
    public class TiController : Controller
    {
        #region Geral
        [HttpGet]
        public ActionResult Index()
        {
            List<NOW> ListaNow = new List<NOW>();
            ListaNow = TiDAO.listar();
            return View(ListaNow);
        }

        [HttpGet]
        public ActionResult TiNOW(int Id_Now)
        {
            NOW now = NowDAO.pesquisarID(Id_Now);
            return View(now);
        }

        [HttpPost]
        public ActionResult TiNOW(NOW now)
        {
            TiDAO.CadastrarTi(now);
            return RedirectToAction("Index");
        }
        #endregion
        
    }
}

FormularioNOW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Projeto Now", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Novo NOW", "GerarNOW", "Geral")</li>
                        <li>@Html.ActionLink("Dashboard", "Index", "Geral")</li>
                        <li>@Html.ActionLink("Pesquisar", "Pesquisar", "Geral")</li>
                        <li>
                            <a href="@Url.Action("","",null)" data-toggle = "dropdown"><span>Setores <i class="fa fa-caret-down"></i></span></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Engenharia", "Index", "Engenharia")</li>
                                <li>@Html.ActionLink("Compras", "Index", "Compras")</li>
                                <li>@Html.ActionLink("T.I", "Index", "Ti")</li>
                                <li>@Html.ActionLink("Prod Soft", "Index", "ProdSoft")</li>
                                <li>@Html.ActionLink("Produto", "Index", "Produto")</li>
                                <li>@Html.ActionLink("Qualidade", "Index", "Qualidade")</li>
                                <li>@Html.ActionLink("Financeiro", "Index", "Financeiro")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Flávio Macedo - Projeto NOW</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>